### ISSUE TITLE
Not copying uuid.UUID from github.com/satori/go.uuid

### ISSUE THREAD

**Issue by RangelReale** [ulule/deepcopier#16]
The type uuid.UUID from github.com/satori/go.uuid is silently ignored, it is not copied and no error is issued.

Debugging the source code, the problem seems to be that the "isNullableType" function detects the uuid.UUID class as a nullable just because it implements "*driver.Valuer", which is not true.

**Comment by thoas** [comment]
fixed by @gillesfabio
